"""empty message

Revision ID: 3726c360f2db
Revises: 3c95cd0e6040
Create Date: 2019-05-18 13:16:36.628833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3726c360f2db'
down_revision = '3c95cd0e6040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log__deleted__student',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('STUDENT_KEY', sa.String(length=16), nullable=False),
    sa.Column('FIRSTNAME', sa.String(length=50), nullable=True),
    sa.Column('LASTNAME', sa.String(length=50), nullable=True),
    sa.Column('ENROLLMENT_NO', sa.String(length=15), nullable=True),
    sa.Column('BRANCH', sa.String(length=50), nullable=True),
    sa.Column('SEM', sa.Integer(), nullable=True),
    sa.Column('COLLEGE', sa.String(length=200), nullable=True),
    sa.Column('EMAIL', sa.String(length=80), nullable=True),
    sa.Column('MOBILE', sa.BigInteger(), nullable=True),
    sa.Column('REG_DATE', sa.DateTime(), nullable=False),
    sa.Column('EVENT_1', sa.String(length=80), nullable=True),
    sa.Column('EVENT_2', sa.String(length=80), nullable=True),
    sa.Column('CAMP_ID', sa.Integer(), nullable=True),
    sa.Column('DELETED_DATE', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ID', 'STUDENT_KEY'),
    sa.UniqueConstraint('EMAIL')
    )
    op.create_table('log_deleted_students',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('STUDENT_KEY', sa.String(length=50), nullable=True),
    sa.Column('FIRSTNAME', sa.String(length=50), nullable=True),
    sa.Column('LASTNAME', sa.String(length=50), nullable=True),
    sa.Column('ENROLLMENT_NO', sa.String(length=15), nullable=True),
    sa.Column('BRANCH', sa.String(length=50), nullable=True),
    sa.Column('SEM', sa.Integer(), nullable=True),
    sa.Column('COLLEGE', sa.String(length=200), nullable=True),
    sa.Column('EMAIL', sa.String(length=80), nullable=True),
    sa.Column('MOBILE', sa.BigInteger(), nullable=True),
    sa.Column('EVENT_1', sa.String(length=80), nullable=True),
    sa.Column('EVENT_2', sa.String(length=80), nullable=True),
    sa.Column('CAMP_ID', sa.Integer(), nullable=True),
    sa.Column('DELETED_DATE', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_deleted_students')
    op.drop_table('log__deleted__student')
    # ### end Alembic commands ###
