"""empty message

Revision ID: 3c95cd0e6040
Revises: a86fe20fae1b
Create Date: 2019-05-18 11:46:25.379544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c95cd0e6040'
down_revision = 'a86fe20fae1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_data',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('STUDENT_KEY', sa.String(length=16), nullable=False),
    sa.Column('FIRSTNAME', sa.String(length=50), nullable=True),
    sa.Column('LASTNAME', sa.String(length=50), nullable=True),
    sa.Column('ENROLLMENT_NO', sa.String(length=15), nullable=True),
    sa.Column('BRANCH', sa.String(length=50), nullable=True),
    sa.Column('SEM', sa.Integer(), nullable=True),
    sa.Column('COLLEGE', sa.String(length=200), nullable=True),
    sa.Column('EMAIL', sa.String(length=80), nullable=True),
    sa.Column('MOBILE', sa.BigInteger(), nullable=True),
    sa.Column('REG_DATE', sa.DateTime(), nullable=False),
    sa.Column('EVENT_1', sa.String(length=80), nullable=True),
    sa.Column('EVENT_2', sa.String(length=80), nullable=True),
    sa.Column('CAMP_ID', sa.Integer(), nullable=True),
    sa.Column('LAST_LOGIN', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID', 'STUDENT_KEY'),
    sa.UniqueConstraint('EMAIL')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_data')
    # ### end Alembic commands ###
