"""empty message

Revision ID: dbc3c3efe90c
Revises: 
Create Date: 2019-04-19 12:41:28.428933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbc3c3efe90c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigner', sa.Column('STATUS', sa.String(length=10), nullable=True))
    op.alter_column('campaigner', 'BRANCH',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('campaigner', 'EMAIL',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('campaigner', 'ENROLLMENT_NO',
               existing_type=mysql.BIGINT(display_width=11),
               nullable=True)
    op.alter_column('campaigner', 'FIRSTNAME',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('campaigner', 'LASTNAME',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('campaigner', 'MOBILE',
               existing_type=mysql.BIGINT(display_width=10),
               nullable=True)
    op.alter_column('campaigner', 'PASSWORD',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('campaigner', 'SEM',
               existing_type=mysql.INTEGER(display_width=1),
               nullable=True)
    op.drop_index('ENROLLMENT_NO', table_name='campaigner')
    op.drop_index('MOBILE', table_name='campaigner')
    op.add_column('student_data', sa.Column('SEM', sa.Integer(), nullable=True))
    op.alter_column('student_data', 'BRANCH',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('student_data', 'CAMP_ID',
               existing_type=mysql.INTEGER(display_width=6),
               nullable=True)
    op.alter_column('student_data', 'COLLEGE',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('student_data', 'EMAIL',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('student_data', 'ENROLLMENT_NO',
               existing_type=mysql.BIGINT(display_width=11),
               nullable=True)
    op.alter_column('student_data', 'FIRSTNAME',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('student_data', 'LASTNAME',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('student_data', 'LAST_LOGIN',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('student_data', 'MOBILE',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.drop_index('ENROLLMENT_NO', table_name='student_data')
    op.drop_index('MOBILE', table_name='student_data')
    op.drop_column('student_data', 'SEMESTER')
    op.add_column('users', sa.Column('ID', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['PRIVILEGE'])
    op.create_unique_constraint(None, 'users', ['PASSWORD'])
    op.create_unique_constraint(None, 'users', ['EMAIL'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'ID')
    op.add_column('student_data', sa.Column('SEMESTER', mysql.INTEGER(display_width=1), autoincrement=False, nullable=False))
    op.create_index('MOBILE', 'student_data', ['MOBILE'], unique=True)
    op.create_index('ENROLLMENT_NO', 'student_data', ['ENROLLMENT_NO'], unique=True)
    op.alter_column('student_data', 'MOBILE',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('student_data', 'LAST_LOGIN',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('student_data', 'LASTNAME',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('student_data', 'FIRSTNAME',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('student_data', 'ENROLLMENT_NO',
               existing_type=mysql.BIGINT(display_width=11),
               nullable=False)
    op.alter_column('student_data', 'EMAIL',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('student_data', 'COLLEGE',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('student_data', 'CAMP_ID',
               existing_type=mysql.INTEGER(display_width=6),
               nullable=False)
    op.alter_column('student_data', 'BRANCH',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_column('student_data', 'SEM')
    op.create_index('MOBILE', 'campaigner', ['MOBILE'], unique=True)
    op.create_index('ENROLLMENT_NO', 'campaigner', ['ENROLLMENT_NO'], unique=True)
    op.alter_column('campaigner', 'SEM',
               existing_type=mysql.INTEGER(display_width=1),
               nullable=False)
    op.alter_column('campaigner', 'PASSWORD',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('campaigner', 'MOBILE',
               existing_type=mysql.BIGINT(display_width=10),
               nullable=False)
    op.alter_column('campaigner', 'LASTNAME',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('campaigner', 'FIRSTNAME',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('campaigner', 'ENROLLMENT_NO',
               existing_type=mysql.BIGINT(display_width=11),
               nullable=False)
    op.alter_column('campaigner', 'EMAIL',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('campaigner', 'BRANCH',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_column('campaigner', 'STATUS')
    # ### end Alembic commands ###
